version: "3.7"
 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapper
    restart: on-failure:5 
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8000 
  redis:
    image: redislabs/rejson:latest
    logging:
      driver: "none"
    container_name: redis-json
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    ports:
      - "6380:6379"