version: "3.7"
 
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapper
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8000 